name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Decker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./docker/pandoc/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pandoc:latest
        chache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/pandoc:buildcache
        chache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/pandoc:buildcache,mode=max
