name: test-dockerfile
on: [push]
jobs:
    test-dockerfile:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: build-dockerfile
